spring.application.name=devshowcase-api

# Ativar a console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração da base de dados H2 ou PostgreSQL (usando variáveis de ambiente com fallback para H2)
spring.datasource.url=${DB_URL:jdbc:h2:mem:devshowcasedb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}

# Configuração do JPA / Hibernate
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
